import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hello Next | App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-7xl mx-auto px-10 lg:px-0`}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
